# Conversation states stored in context.user_data["state"]
IDLE = "idle"
WAIT_URL = "wait_url"
WAIT_FILE = "wait_file"
ADMIN_SEARCH = "admin_search"
ADMIN_VIEW_USER = "admin_view_user"
ADMIN_ADD_CHANNEL = "admin_add_channel"
ADMIN_SET_GOOGLE_ID = "admin_set_google_id"
ADMIN_SET_GOOGLE_SECRET = "admin_set_google_secret"
ADMIN_TUTORIAL_ADD = "admin_tutorial_add"
ADMIN_SW_ADD = "admin_sw_add"
